### ISSUE TITLE
Errors during task execution do not fail build/deployment

### ISSUE THREAD

**Issue by jmezach** [jessehouwing/vsts-extension-tasks#17]
I've been trying out these extension to model a release pipeline for my own extension. However, it seems that errors that occur while the Publish task is executing do not automatically cause the deployment to fail, as can be seen in the following screenshot:

![image](https://cloud.githubusercontent.com/assets/1225489/13983741/cc5309d0-f0f1-11e5-96bd-6c8d82d75473.png)

This doesn't seem right to me.

**Comment by jessehouwing** [comment]
Looks like your extension is "stuck" on an older version. Can you check the
task version in the debug output and in the Ui and compare that with the
latest erosion on the marketplace?

I replaced the code that stops on error with a throw exception quite some
time ago, but it seems that some changes to the task manifest can get a
task to not auto-update.

Making a change to the configuration and saving it sometimes triggers the
update. But I've had situations where I've had to uninstalled / reinstall
the task from the account.

I'm filing a bug with the build team to see what they think about these
issues.

**Comment by jmezach** [comment]
I've had a look at the output but it looks like I'm using the most recent version:

```
2016-03-23T10:01:15.0522788Z Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\ExtensionPublishTask\0.0.749\vsts-extension-publish.ps1
```

0.0.749 seems to be the latest version on the marketplace.

**Comment by jessehouwing** [comment]
I'm going to have a look at what's going wrong.

**Comment by jessehouwing** [comment]
The strange thing is that the code that once wrote the `###vso[tasktype.logissue...` has long been removed and I've replaced it with:

```
                $messages | %{ Write-Error $_ }
                throw "Tfx returned an error."
            }
```

Leading me to believe that somehow your build agent is using an old version of the task. Judging from the path though, you're using the hosted build, which should always be using the latest version... Any chance you could set `system.debug` to true and send me the output?

**Comment by jessehouwing** [comment]
See: https://github.com/jessehouwing/vsts-extension-tasks/wiki/How-to-file-an-issue

**Comment by jmezach** [comment]
Sure, here you go:

[ReleaseLogs_5.zip](https://github.com/jessehouwing/vsts-extension-tasks/files/186017/ReleaseLogs_5.zip)

**Comment by jessehouwing** [comment]
it look/s like it's using a different version now, the ##vso line is gone,
which should be, but the throw is somehow ignored. I've asked the build
team what's going on there, because throwing an exception should do the
magic.

**Comment by jessehouwing** [comment]
I just released version 0.0.750 in hopes it solves the issue while I wait for a reply from Microsoft.

**Comment by jessehouwing** [comment]
Doesn't seem to work. ARGH!

**Comment by jmezach** [comment]
Just tried it and the issue seems to be fixed now. Thanks for the help.
