### ISSUE TITLE
Version parsing error when not overriding version

### ISSUE THREAD

**Issue by qetza** [jessehouwing/vsts-extension-tasks#20]
Hi Jesse,
If your build number doesn't contains a version and you leave your task configured as default (`override extension version` = false, `version` = $(Build.BuildNumber, `override build version` = true) then you get a parse error in Update-InternalVersion.
This took me some time to understand the issue (i had to look at the code) because as the default value of `override extension version` is false you don't see the input `override build version` and it's value of true.
If `override extension version` is false i think you should not try to update any version.

**Comment by jessehouwing** [comment]
Thanks! I generally have a Build number in that field, so it probably always succeeds in that case.
