### ISSUE TITLE
Create tips & tricks article

### ISSUE THREAD

**Issue by jessehouwing** [jessehouwing/vsts-extension-tasks#23]
Include:
- [ ] Create a account-dev visual studio team services account to publish your dev versions to.
- [ ] Follow the Share task with a Install task to push the version to the account-dev.
- [ ] Temporarily share a dev or test version of your task with a user who has an issue to test a fix on their environment.
- [ ] Merge a Tag and Version into the task.json to easily distinguish between tasks on an environment
- [ ] Keep the GUIDs the same across versions if you want to  quickly use a different edition (dev, test, release) of your task on any environment
- [ ] Change the GUIDs across versions if you want to be able to test versions of your tast side-by side. If you do this also include the Extension-TAG in your Task-ID in the task.json, otherwise they'll end up in the same task folder on the build agent and this can lead to interesting behavior.
- [ ] always increase the version number of a task when it's published. 
- [ ] do advanced crazy shit using the overrides option
- [ ] use a Search & replace task to quickly update task manifests: https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens (set format to utfs-8, no-BOM)

**Comment by jessehouwing** [comment]
This is my replace token configuration: 
![image](https://cloud.githubusercontent.com/assets/4173387/14558210/6b1eccd6-0301-11e6-8654-ddf51ca2d998.png)

**Comment by jdshkolnik** [comment]
@jessehouwing Could you please add a bullet for using with TFS 2015 on-prem? Like how to publish/install to 2015.

**Comment by jessehouwing** [comment]
As this functionality is being merged into the tasks created by Microsoft
DevLabs with the help of other MVPs and ALM Rangers and myself I won't do
any majorly investments into this extension or its documentation. But it's
a fair ask for its replacement.

For now publish to TFS servers works as long as the TFS server supports
basic authentication, which is considered a very bad idea. So let the
publishing url to be the TFS server root (e.g. Https://tfs:443/tfs) that
should work. The user configured to do the publish must be server
administrator. The rest of the process is the same as for VSTS.

Install currently doesn't work, as it's awaiting a pull request merge to
the tfx repository.

**Comment by jdshkolnik** [comment]
Thanks. I've been trying to create a build definition that'll update the extension in TFS once created but am stuck partly because of the install not working.

I understand install and update, and I know what it means to publish to marketplace, but what would publish do against TFS on-premises?

**Comment by jessehouwing** [comment]
On premise publish will make the new version available at the server level
for installation.

Any project collection which already has the extension installed will be
upgraded automatically.

**Comment by jdshkolnik** [comment]
I appreciate the help. I'll keep an eye out for the TFX-CLI update with support for install to TFS.

**Comment by jessehouwing** [comment]
https://github.com/Microsoft/tfs-cli/pull/132
