### ISSUE TITLE
Sharing vsts-extension-shared.psm1

### ISSUE THREAD

**Issue by jdshkolnik** [jessehouwing/vsts-extension-tasks#26]
@jessehouwing Hi. How does `vsts-extension-shared.psm1` get shared to the other task project directories? I see the reference to `vsts-extension-shared.pssproj` in other `*.pssproj` files but nothing that would copy `vsts-extension-shared.psm1` to those task folders. Is it happening in your build definition?

**Comment by jessehouwing** [comment]
Yeah that's a pre-build copy step. And I am using the powershell task
runner with a pre-build action inside Visual Studio.

**Comment by jdshkolnik** [comment]
Whew, +1 for my sanity. I was _this_ close to denouncing you as a witch. Would you be willing to share the pre-build action? It'd save me a bit of time duplicating it.

**Comment by jessehouwing** [comment]
Use [this extension](https://marketplace.visualstudio.com/items?itemName=onlyutkarsh.ExportImportBuildDefinition) to import the attached build definition.

[vsts-extension-tasks.json.txt](https://github.com/jessehouwing/vsts-extension-tasks/files/373916/vsts-extension-tasks.json.txt)

**Comment by jessehouwing** [comment]
Or steal the pre-build.ps from one of my other tasks:
https://github.com/jessehouwing/vsts-tfvc-tasks/blob/master/Pre-Build.ps1

And combine it with:
https://visualstudiogallery.msdn.microsoft.com/e6bf6a3d-7411-4494-8a1e-28c1a8c4ce99

And 
https://github.com/jessehouwing/vsts-tfvc-tasks/blob/master/commands.json

**Comment by jdshkolnik** [comment]
Thank you.

**Comment by jessehouwing** [comment]
I'm now very curious as to what you're up to :)

**Comment by jdshkolnik** [comment]
Email me at jshkolnik@deloitte.com and I'll schedule a call with screen sharing to show you. 

John D. Shkolnik

On Jul 21, 2016, at 1:23 PM, Jesse Houwing notifications@github.com wrote:

I'm now very curious as to what you're up to :)
